#
# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.
#


from collections import Counter

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        #自己写的，用Counter，如果不用呢？
        '''
        return list(Counter(t) - Counter(s))[0]
        '''
        #solution 1，求和
        '''
        sum = 0
        for ch in t:
            sum += ord(ch)
        for ch in s:
            sum -= ord(ch)
        return chr(sum)
        '''
        #solution 2，XOR
        '''
        result = 0
        for ch in t:
            result ^= ord(ch)
        for ch in s:
            result ^= ord(ch)
        return chr(result)
        '''
        #solution 3，python简单判断也可以
        for ch in t:
            if ch not in s or s.count(ch) != t.count(ch):
                return ch
